In [2]:
import numpy as np
x = np.array([[1,2,3], [4,5,6], [7, 8, 9], [10, 11, 12]])
print("x:")
print(x)
print("\nx[1:, :-1]:")
print(x[1:, :-1])

x:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

x[1:, :-1]:
[[ 4  5]
 [ 7  8]
 [10 11]]


In [3]:
import pandas as pd
d = {'name': ["james", "theodore", "jane", "maria"], 
     'score': [4., 3., 2., 5.]}
df = pd.DataFrame(d)
print(df.columns)
print(df)

Index(['name', 'score'], dtype='object')
       name  score
0     james    4.0
1  theodore    3.0
2      jane    2.0
3     maria    5.0
